services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:3.12.14'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'